#!/usr/bin/env ruby

lib = File.expand_path("../../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'gh/events'

begin
  puts GH::Events::Text.translate(STDIN.read, ARGV.first)
rescue GH::Events::Template::UnknownDictFileError => e
  warn(e)
  exit 1
end
